<?php

include_once __DIR__ . '/vendor/autoload.php';

/**
 * Implements hook_library().
 */
function systemix_library() {
    $path = drupal_get_path('module', 'systemix');
    $libraries['systemix.typing_uppercase'] = [
        'title' => 'Systemix Typing Uppercase',
        'website' => 'https://github.com/ijortengab/drupal7-systemix',
        'version' => '1.0.0',
        'js' => [
            $path.'/js/systemix-typing-uppercase.js' => [
                'group' => JS_DEFAULT,
            ],
        ],
    ];
    $libraries['systemix.typing_number'] = [
        'title' => 'Systemix Typing Number',
        'website' => 'https://github.com/ijortengab/drupal7-systemix',
        'version' => '1.0.0',
        'js' => [
            $path.'/js/jquery.inputfilter.js' => [
                'group' => JS_LIBRARY,
            ],
            $path.'/js/systemix-typing-number.js' => [
                'group' => JS_DEFAULT,
            ],
        ],
    ];
    return $libraries;
}

function systemix_systemix_conditional_attached_library() {
   return [
        'systemix_1' => ['systemix', 'systemix.typing_uppercase'],
        'systemix_2' => ['systemix', 'systemix.typing_number'],
    ];
}

/**
 * Implements hook_views_api().
 */
function systemix_views_api() {
    return array(
        'api' => 3,
    );
}

function systemix_menu_alter(&$items) {
    Drupal\systemix\Menu\Menu::autoCreate($items);
    Drupal\systemix\Menu\Menu::disabledDefaultRoute($items);
    Drupal\systemix\Menu\Menu::forwardPageCallback($items);
}

function systemix_ajax_callback($form, $form_state) {
    if (!empty($form_state['triggering_element'])) {
        $callback = $form_state['triggering_element']['#ajax']['callback2'];
        return call_user_func_array(
            $callback,
            [$form, $form_state]
        );
    }
}

function systemix_form_validate_callback($form, &$form_state) {
    if (isset($form['#validate2'])) {
        foreach ($form['#validate2'] as $callback) {
            call_user_func_array(
                $callback,
                [$form, &$form_state]
            );
        }
    }
}

function systemix_form_submit_callback($form, &$form_state) {
    if (isset($form['#submit2'])) {
        foreach ($form['#submit2'] as $callback) {
            call_user_func_array(
                $callback,
                [$form, &$form_state]
            );
        }
    }
}

function systemix_form_actions_submit_redirect($form, &$form_state) {
    $form_state['redirect'] = $form_state['systemix']['redirect'];
}

function systemix_page_callback() {
    $menu_link_get_preferred = menu_link_get_preferred();
    $menu_link_load = menu_link_load(menu_link_get_preferred()['mlid']);
    if (isset($menu_link_load['options']['systemix_page_callback'])) {
        $args = func_get_args();
        return call_user_func_array($menu_link_load['options']['systemix_page_callback'], $args);
    }
    return drupal_not_found();
}
